server {
	listen 443 ssl;
	http2 on;
	server_name gitea.example.com;

	ssl_certificate     /etc/certbot/live/example.com/fullchain.pem;
	ssl_certificate_key /etc/certbot/live/example.com/privkey.pem;
	
	client_max_body_size 0; # Not setting a limit for using registry, set a limit if using in public deployment
	
	location / {
		proxy_pass http://gitea:3000;  # set docker container_name: gitea and attach nginx network
	    
		proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

	    # timeouts for long Git operations
	    proxy_connect_timeout 300;
	    proxy_send_timeout 300;
	    proxy_read_timeout 300;
	    send_timeout 300;	
	}
}
