server {
	listen 443 ssl;
	http2 on;
	server_name example.com www.example.com;

	ssl_certificate     /etc/certbot/live/example.com/fullchain.pem;
	ssl_certificate_key /etc/certbot/live/example.com/privkey.pem;
	
	root /usr/share/sites/<site folder name>; # Give nginx location to site. If usin docker mount location properly as in compose file
	index index.html;
	
	location / {
		try_files $uri $uri/ = 404;	
	}
}